<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.tommytony</groupId>
  <artifactId>war</artifactId>
  <version>2.9.7</version>
  <packaging>jar</packaging>
  <name>War</name>
  <url>http://war.tommytony.com</url>
  <description>Minecraft PVP arenas (called warzones) for a fast-paced and structured PVP experience with TDM, CTF and more!</description>
  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>
  <repositories>
    <repository>
      <id>codemc-repo</id>
      <url>https://repo.codemc.io/repository/maven-public/</url>
    </repository>
    <repository>
        <id>jitpack.io</id>
        <url>https://jitpack.io</url>
      </repository>
    <repository>
      <id>enginehub-maven</id>
      <url>https://maven.enginehub.org/repo/</url>
    </repository>
    <repository>
      <id>spigot-repo</id>
      <url>https://hub.spigotmc.org/nexus/content/groups/public/</url>
    </repository>
    <repository>
      <id>papermc</id>
      <url>https://repo.papermc.io/repository/maven-public/</url>
    </repository>
    <repository>
      <id>krypton</id>
      <url>https://repo.kryptonmc.org/releases</url>
    </repository>
  </repositories>
  <issueManagement>
    <system>Github issues</system>
    <url>https://github.com/taoneill/war/issues</url>
  </issueManagement>
  <scm>
    <connection>scm:git:git://github.com/taoneill/war.git</connection>
    <developerConnection>scm:git:git@github.com:taoneill/war.git</developerConnection>
    <tag>HEAD</tag>
    <url>https://github.com/taoneill/war</url>
  </scm>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.intellectualsites.bom</groupId>
        <artifactId>bom-1.18.x</artifactId>
        <version>1.28</version>
        <scope>import</scope>
        <type>pom</type>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <distributionManagement>
    <repository>
      <id>maven.cmastudios.me</id>
      <url>s3://maven.cmastudios.me/</url>
    </repository>
  </distributionManagement>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>2.3.2</version>
        <configuration>
          <source>17</source>
          <target>17</target>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-resources-plugin</artifactId>
        <version>3.3.1</version>
        <configuration>
          <encoding>UTF-8</encoding>
          <nonFilteredFileExtensions>
            <nonFilteredFileExtension>properties</nonFilteredFileExtension>
          </nonFilteredFileExtensions>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <version>3.5.1</version>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
            <configuration>
              <artifactSet>
                <includes>
                  <include>org.bstats</include>
                </includes>
              </artifactSet>
              <minimizeJar>true</minimizeJar>
              <relocations>
                <relocation>
                  <pattern>org.bstats</pattern>
                  <shadedPattern>com.tommytony.war.metrics</shadedPattern>
                </relocation>
              </relocations>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
    <extensions>
      <extension>
        <groupId>org.kuali.maven.wagons</groupId>
        <artifactId>maven-s3-wagon</artifactId>
        <version>1.2.1</version>
      </extension>
    </extensions>
    <resources>
      <resource>
        <filtering>true</filtering>
        <directory>${basedir}/src/main/resources/</directory>
      </resource>
    </resources>
  </build>
  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.13.2</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>commons-lang</groupId>
      <artifactId>commons-lang</artifactId>
      <version>2.6</version>
    </dependency>
    <dependency>
          <groupId>com.github.NEZNAMY</groupId>
          <artifactId>TAB-API</artifactId>
          <version>5.4.0</version>
          <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-core</artifactId>
      <version>2.19.0</version> <!-- replace with the version you are targeting -->
    </dependency>
    <dependency>
      <groupId>com.fastasyncworldedit</groupId>
      <artifactId>FastAsyncWorldEdit-Core</artifactId>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>com.fastasyncworldedit</groupId>
      <artifactId>FastAsyncWorldEdit-Bukkit</artifactId>
      <scope>provided</scope>
      <exclusions>
        <exclusion>
          <artifactId>FastAsyncWorldEdit-Core</artifactId>
          <groupId>*</groupId>
        </exclusion>
      </exclusions>
    </dependency>
    <!-- <dependency>
      <groupId>me.filoghost.holographicdisplays</groupId>
      <artifactId>holographicdisplays-api</artifactId>
      <version>3.0.0</version>
      <scope>provided</scope>
    </dependency> -->
    <dependency>
        <groupId>com.github.decentsoftware-eu</groupId>
        <artifactId>decentholograms</artifactId>
        <version>2.9.9</version>
        <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.spigotmc</groupId>
      <artifactId>spigot-api</artifactId>
      <!-- <version>1.20.1-R0.1-SNAPSHOT</version> -->
      <version>1.21.11-R0.1-SNAPSHOT</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-core</artifactId>
      <version>4.1.0</version>
      <type>jar</type>
      <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>com.github.MilkBowl</groupId>
        <artifactId>VaultAPI</artifactId>
        <version>1.7</version>
        <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.bstats</groupId>
      <artifactId>bstats-bukkit</artifactId>
      <version>2.2.1</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.h2database</groupId>
      <artifactId>h2</artifactId>
      <version>2.2.224</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>
</project>
